/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DailyStats { 'total' : bigint, 'completed' : bigint }
export interface Entity {
  'id' : string,
  'title' : string,
  'dayOfWeek' : bigint,
  'createdAt' : bigint,
  'completed' : boolean,
  'taskOrder' : bigint,
  'category' : string,
  'priority' : string,
  'weekStart' : string,
}
export interface Entity__1 {
  'id' : string,
  'title' : string,
  'monthPlanId' : string,
  'completed' : boolean,
  'description' : string,
  'isFrog' : boolean,
  'deadline' : string,
  'weekNumber' : bigint,
  'priority' : string,
}
export interface Entity__2 {
  'id' : string,
  'month' : bigint,
  'title' : string,
  'year' : bigint,
  'linkedGoalId' : string,
}
export interface Entity__3 {
  'id' : string,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'category' : string,
  'priority' : string,
}
export interface MonthlyStats { 'total' : bigint, 'completed' : bigint }
export interface MonthlyTaskStats { 'total' : bigint, 'completed' : bigint }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyStats { 'total' : bigint, 'completed' : bigint }
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createDayTask' : ActorMethod<
    [string, string, boolean, bigint, string, string, string, bigint],
    undefined
  >,
  'createGoal' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'createMonthPlan' : ActorMethod<
    [string, bigint, bigint, string, string],
    undefined
  >,
  'createMonthTask' : ActorMethod<
    [string, string, string, string, string, string, bigint, boolean, boolean],
    undefined
  >,
  'deleteDayTask' : ActorMethod<[string], undefined>,
  'deleteGoal' : ActorMethod<[string], undefined>,
  'deleteMonthPlan' : ActorMethod<[string], undefined>,
  'deleteMonthTask' : ActorMethod<[string], undefined>,
  'getAllDayTasks' : ActorMethod<[], Array<Entity>>,
  'getAllGoals' : ActorMethod<[], Array<Entity__3>>,
  'getAllMonthPlans' : ActorMethod<[], Array<Entity__2>>,
  'getAllMonthTasks' : ActorMethod<[], Array<Entity__1>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyStats' : ActorMethod<[string], DailyStats>,
  'getDayTasksByWeek' : ActorMethod<[string], Array<Entity>>,
  'getMonthlyStats' : ActorMethod<[bigint, bigint], MonthlyStats>,
  'getMonthlyTaskStats' : ActorMethod<[bigint, bigint], MonthlyTaskStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWeeklyStats' : ActorMethod<[string], WeeklyStats>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reorderDayTasks' : ActorMethod<[Array<string>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateDayTask' : ActorMethod<
    [string, string, boolean, bigint, string, string, string, bigint],
    undefined
  >,
  'updateGoal' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'updateMonthPlan' : ActorMethod<
    [string, bigint, bigint, string, string],
    undefined
  >,
  'updateMonthTask' : ActorMethod<
    [string, string, string, string, string, string, bigint, boolean, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];