/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Entity = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'dayOfWeek' : IDL.Nat,
  'createdAt' : IDL.Int,
  'completed' : IDL.Bool,
  'taskOrder' : IDL.Nat,
  'category' : IDL.Text,
  'priority' : IDL.Text,
  'weekStart' : IDL.Text,
});
export const Entity__3 = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'priority' : IDL.Text,
});
export const Entity__2 = IDL.Record({
  'id' : IDL.Text,
  'month' : IDL.Nat,
  'title' : IDL.Text,
  'year' : IDL.Nat,
  'linkedGoalId' : IDL.Text,
});
export const Entity__1 = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'monthPlanId' : IDL.Text,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'isFrog' : IDL.Bool,
  'deadline' : IDL.Text,
  'weekNumber' : IDL.Nat,
  'priority' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DailyStats = IDL.Record({
  'total' : IDL.Nat,
  'completed' : IDL.Nat,
});
export const MonthlyStats = IDL.Record({
  'total' : IDL.Nat,
  'completed' : IDL.Nat,
});
export const MonthlyTaskStats = IDL.Record({
  'total' : IDL.Nat,
  'completed' : IDL.Nat,
});
export const WeeklyStats = IDL.Record({
  'total' : IDL.Nat,
  'completed' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createDayTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'createGoal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createMonthPlan' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createMonthTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
  'deleteDayTask' : IDL.Func([IDL.Text], [], []),
  'deleteGoal' : IDL.Func([IDL.Text], [], []),
  'deleteMonthPlan' : IDL.Func([IDL.Text], [], []),
  'deleteMonthTask' : IDL.Func([IDL.Text], [], []),
  'getAllDayTasks' : IDL.Func([], [IDL.Vec(Entity)], ['query']),
  'getAllGoals' : IDL.Func([], [IDL.Vec(Entity__3)], ['query']),
  'getAllMonthPlans' : IDL.Func([], [IDL.Vec(Entity__2)], ['query']),
  'getAllMonthTasks' : IDL.Func([], [IDL.Vec(Entity__1)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyStats' : IDL.Func([IDL.Text], [DailyStats], ['query']),
  'getDayTasksByWeek' : IDL.Func([IDL.Text], [IDL.Vec(Entity)], ['query']),
  'getMonthlyStats' : IDL.Func([IDL.Nat, IDL.Nat], [MonthlyStats], ['query']),
  'getMonthlyTaskStats' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [MonthlyTaskStats],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWeeklyStats' : IDL.Func([IDL.Text], [WeeklyStats], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderDayTasks' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateDayTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [],
      [],
    ),
  'updateGoal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateMonthPlan' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateMonthTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Bool,
        IDL.Bool,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Entity = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'dayOfWeek' : IDL.Nat,
    'createdAt' : IDL.Int,
    'completed' : IDL.Bool,
    'taskOrder' : IDL.Nat,
    'category' : IDL.Text,
    'priority' : IDL.Text,
    'weekStart' : IDL.Text,
  });
  const Entity__3 = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'priority' : IDL.Text,
  });
  const Entity__2 = IDL.Record({
    'id' : IDL.Text,
    'month' : IDL.Nat,
    'title' : IDL.Text,
    'year' : IDL.Nat,
    'linkedGoalId' : IDL.Text,
  });
  const Entity__1 = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'monthPlanId' : IDL.Text,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'isFrog' : IDL.Bool,
    'deadline' : IDL.Text,
    'weekNumber' : IDL.Nat,
    'priority' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DailyStats = IDL.Record({ 'total' : IDL.Nat, 'completed' : IDL.Nat });
  const MonthlyStats = IDL.Record({ 'total' : IDL.Nat, 'completed' : IDL.Nat });
  const MonthlyTaskStats = IDL.Record({
    'total' : IDL.Nat,
    'completed' : IDL.Nat,
  });
  const WeeklyStats = IDL.Record({ 'total' : IDL.Nat, 'completed' : IDL.Nat });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createDayTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'createGoal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createMonthPlan' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createMonthTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'deleteDayTask' : IDL.Func([IDL.Text], [], []),
    'deleteGoal' : IDL.Func([IDL.Text], [], []),
    'deleteMonthPlan' : IDL.Func([IDL.Text], [], []),
    'deleteMonthTask' : IDL.Func([IDL.Text], [], []),
    'getAllDayTasks' : IDL.Func([], [IDL.Vec(Entity)], ['query']),
    'getAllGoals' : IDL.Func([], [IDL.Vec(Entity__3)], ['query']),
    'getAllMonthPlans' : IDL.Func([], [IDL.Vec(Entity__2)], ['query']),
    'getAllMonthTasks' : IDL.Func([], [IDL.Vec(Entity__1)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyStats' : IDL.Func([IDL.Text], [DailyStats], ['query']),
    'getDayTasksByWeek' : IDL.Func([IDL.Text], [IDL.Vec(Entity)], ['query']),
    'getMonthlyStats' : IDL.Func([IDL.Nat, IDL.Nat], [MonthlyStats], ['query']),
    'getMonthlyTaskStats' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [MonthlyTaskStats],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWeeklyStats' : IDL.Func([IDL.Text], [WeeklyStats], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderDayTasks' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateDayTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [],
        [],
      ),
    'updateGoal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateMonthPlan' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateMonthTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Bool,
          IDL.Bool,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };